version: "3.7"
services:
  web:
    container_name: agent-stationnement
    build: .
    ports:
      - 3070:3070
    depends_on:
      - mongodb
    volumes:
      - .:/code
  mongodb:
    image: mongo
    container_name: example-mongodb
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data: